// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'af2b89a543a858ed67dd91fb9ad4eaa69076fb53e0cadba5a0717e1cd2e6fdd1'>;
export type ExecutionHash =
  ExecutionHashBase<'3a78e1c2935418ea4d057326b99e1f40f5040ebfd15664b72a383edd9e8e3ab8'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly AuditLog: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly signRequestId: CodecTypes['pg/uuid@1']['output'] | null;
      readonly actorUserId: CodecTypes['pg/text@1']['output'] | null;
      readonly action:
        | 'SIGN_REQUEST_CREATED'
        | 'DOCUMENT_CREATED'
        | 'DOCUMENT_OPENED'
        | 'PLACEMENT_CREATED'
        | 'PLACEMENT_UPDATED'
        | 'SIGN_ATTEMPT'
        | 'PIN_FAILED'
        | 'SIGNED'
        | 'REJECTED'
        | 'FAILED'
        | 'CANCELLED';
      readonly ipAddress: CodecTypes['pg/text@1']['output'] | null;
      readonly userAgent: CodecTypes['pg/text@1']['output'] | null;
      readonly metadata: CodecTypes['pg/json@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Document: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly signRequestId: CodecTypes['pg/uuid@1']['output'];
      readonly type: 'ORIGINAL' | 'SIGNED' | 'ATTACHMENT';
      readonly fileKey: CodecTypes['pg/text@1']['output'];
      readonly hash: CodecTypes['pg/text@1']['output'] | null;
      readonly mimeType: CodecTypes['pg/text@1']['output'] | null;
      readonly fileSize: CodecTypes['pg/int4@1']['output'] | null;
      readonly locked: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Signature: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly signRequestId: CodecTypes['pg/uuid@1']['output'];
      readonly documentId: CodecTypes['pg/uuid@1']['output'];
      readonly signerUserId: CodecTypes['pg/text@1']['output'];
      readonly documentHash: CodecTypes['pg/text@1']['output'];
      readonly algorithm: CodecTypes['pg/text@1']['output'];
      readonly signatureValue: CodecTypes['pg/text@1']['output'];
      readonly certificateSerial: CodecTypes['pg/text@1']['output'] | null;
      readonly certificateIssuer: CodecTypes['pg/text@1']['output'] | null;
      readonly signedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly SignaturePlacement: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly signRequestId: CodecTypes['pg/uuid@1']['output'];
      readonly documentId: CodecTypes['pg/uuid@1']['output'];
      readonly signerUserId: CodecTypes['pg/text@1']['output'];
      readonly type: 'SIGNATURE' | 'INITIAL' | 'STAMP' | 'QR_CODE';
      readonly page: CodecTypes['pg/int4@1']['output'];
      readonly x: CodecTypes['pg/float8@1']['output'];
      readonly y: CodecTypes['pg/float8@1']['output'];
      readonly width: CodecTypes['pg/float8@1']['output'];
      readonly height: CodecTypes['pg/float8@1']['output'];
      readonly sequence: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly SignerCredential: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
      readonly pinHash: CodecTypes['pg/text@1']['output'];
      readonly failedAttempt: CodecTypes['pg/int4@1']['output'];
      readonly lockedUntil: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly active: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly SignRequest: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly referenceId: CodecTypes['pg/text@1']['output'];
      readonly signerUserId: CodecTypes['pg/text@1']['output'];
      readonly villageId: CodecTypes['pg/text@1']['output'] | null;
      readonly status: 'PENDING' | 'PROCESSING' | 'SIGNED' | 'REJECTED' | 'FAILED' | 'CANCELLED';
      readonly rejectionReason: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly signedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly rejectedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly AuditLog: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly signRequestId: CodecTypes['pg/uuid@1']['input'] | null;
      readonly actorUserId: CodecTypes['pg/text@1']['input'] | null;
      readonly action:
        | 'SIGN_REQUEST_CREATED'
        | 'DOCUMENT_CREATED'
        | 'DOCUMENT_OPENED'
        | 'PLACEMENT_CREATED'
        | 'PLACEMENT_UPDATED'
        | 'SIGN_ATTEMPT'
        | 'PIN_FAILED'
        | 'SIGNED'
        | 'REJECTED'
        | 'FAILED'
        | 'CANCELLED';
      readonly ipAddress: CodecTypes['pg/text@1']['input'] | null;
      readonly userAgent: CodecTypes['pg/text@1']['input'] | null;
      readonly metadata: CodecTypes['pg/json@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Document: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly signRequestId: CodecTypes['pg/uuid@1']['input'];
      readonly type: 'ORIGINAL' | 'SIGNED' | 'ATTACHMENT';
      readonly fileKey: CodecTypes['pg/text@1']['input'];
      readonly hash: CodecTypes['pg/text@1']['input'] | null;
      readonly mimeType: CodecTypes['pg/text@1']['input'] | null;
      readonly fileSize: CodecTypes['pg/int4@1']['input'] | null;
      readonly locked: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Signature: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly signRequestId: CodecTypes['pg/uuid@1']['input'];
      readonly documentId: CodecTypes['pg/uuid@1']['input'];
      readonly signerUserId: CodecTypes['pg/text@1']['input'];
      readonly documentHash: CodecTypes['pg/text@1']['input'];
      readonly algorithm: CodecTypes['pg/text@1']['input'];
      readonly signatureValue: CodecTypes['pg/text@1']['input'];
      readonly certificateSerial: CodecTypes['pg/text@1']['input'] | null;
      readonly certificateIssuer: CodecTypes['pg/text@1']['input'] | null;
      readonly signedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly SignaturePlacement: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly signRequestId: CodecTypes['pg/uuid@1']['input'];
      readonly documentId: CodecTypes['pg/uuid@1']['input'];
      readonly signerUserId: CodecTypes['pg/text@1']['input'];
      readonly type: 'SIGNATURE' | 'INITIAL' | 'STAMP' | 'QR_CODE';
      readonly page: CodecTypes['pg/int4@1']['input'];
      readonly x: CodecTypes['pg/float8@1']['input'];
      readonly y: CodecTypes['pg/float8@1']['input'];
      readonly width: CodecTypes['pg/float8@1']['input'];
      readonly height: CodecTypes['pg/float8@1']['input'];
      readonly sequence: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly SignerCredential: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
      readonly pinHash: CodecTypes['pg/text@1']['input'];
      readonly failedAttempt: CodecTypes['pg/int4@1']['input'];
      readonly lockedUntil: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly active: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly SignRequest: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly referenceId: CodecTypes['pg/text@1']['input'];
      readonly signerUserId: CodecTypes['pg/text@1']['input'];
      readonly villageId: CodecTypes['pg/text@1']['input'] | null;
      readonly status: 'PENDING' | 'PROCESSING' | 'SIGNED' | 'REJECTED' | 'FAILED' | 'CANCELLED';
      readonly rejectionReason: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly signedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly rejectedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly audit_logs: {
      readonly action:
        | 'SIGN_REQUEST_CREATED'
        | 'DOCUMENT_CREATED'
        | 'DOCUMENT_OPENED'
        | 'PLACEMENT_CREATED'
        | 'PLACEMENT_UPDATED'
        | 'SIGN_ATTEMPT'
        | 'PIN_FAILED'
        | 'SIGNED'
        | 'REJECTED'
        | 'FAILED'
        | 'CANCELLED';
      readonly actor_user_id: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly ip_address: CodecTypes['pg/text@1']['output'] | null;
      readonly metadata: CodecTypes['pg/json@1']['output'] | null;
      readonly sign_request_id: CodecTypes['pg/uuid@1']['output'] | null;
      readonly user_agent: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly documents: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly file_key: CodecTypes['pg/text@1']['output'];
      readonly file_size: CodecTypes['pg/int4@1']['output'] | null;
      readonly hash: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly locked: CodecTypes['pg/bool@1']['output'];
      readonly mime_type: CodecTypes['pg/text@1']['output'] | null;
      readonly sign_request_id: CodecTypes['pg/uuid@1']['output'];
      readonly type: 'ORIGINAL' | 'SIGNED' | 'ATTACHMENT';
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly sign_requests: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly reference_id: CodecTypes['pg/text@1']['output'];
      readonly rejected_at: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly rejection_reason: CodecTypes['pg/text@1']['output'] | null;
      readonly signed_at: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly signer_user_id: CodecTypes['pg/text@1']['output'];
      readonly status: 'PENDING' | 'PROCESSING' | 'SIGNED' | 'REJECTED' | 'FAILED' | 'CANCELLED';
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly village_id: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly signature_placements: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly document_id: CodecTypes['pg/uuid@1']['output'];
      readonly height: CodecTypes['pg/float8@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly page: CodecTypes['pg/int4@1']['output'];
      readonly sequence: CodecTypes['pg/int4@1']['output'];
      readonly sign_request_id: CodecTypes['pg/uuid@1']['output'];
      readonly signer_user_id: CodecTypes['pg/text@1']['output'];
      readonly type: 'SIGNATURE' | 'INITIAL' | 'STAMP' | 'QR_CODE';
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly width: CodecTypes['pg/float8@1']['output'];
      readonly x: CodecTypes['pg/float8@1']['output'];
      readonly y: CodecTypes['pg/float8@1']['output'];
    };
    readonly signatures: {
      readonly algorithm: CodecTypes['pg/text@1']['output'];
      readonly certificate_issuer: CodecTypes['pg/text@1']['output'] | null;
      readonly certificate_serial: CodecTypes['pg/text@1']['output'] | null;
      readonly document_hash: CodecTypes['pg/text@1']['output'];
      readonly document_id: CodecTypes['pg/uuid@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly sign_request_id: CodecTypes['pg/uuid@1']['output'];
      readonly signature_value: CodecTypes['pg/text@1']['output'];
      readonly signed_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly signer_user_id: CodecTypes['pg/text@1']['output'];
    };
    readonly signer_credentials: {
      readonly active: CodecTypes['pg/bool@1']['output'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly failed_attempt: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly locked_until: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly pin_hash: CodecTypes['pg/text@1']['output'];
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly user_id: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly audit_logs: {
      readonly action:
        | 'SIGN_REQUEST_CREATED'
        | 'DOCUMENT_CREATED'
        | 'DOCUMENT_OPENED'
        | 'PLACEMENT_CREATED'
        | 'PLACEMENT_UPDATED'
        | 'SIGN_ATTEMPT'
        | 'PIN_FAILED'
        | 'SIGNED'
        | 'REJECTED'
        | 'FAILED'
        | 'CANCELLED';
      readonly actor_user_id: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly ip_address: CodecTypes['pg/text@1']['input'] | null;
      readonly metadata: CodecTypes['pg/json@1']['input'] | null;
      readonly sign_request_id: CodecTypes['pg/uuid@1']['input'] | null;
      readonly user_agent: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly documents: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly file_key: CodecTypes['pg/text@1']['input'];
      readonly file_size: CodecTypes['pg/int4@1']['input'] | null;
      readonly hash: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly locked: CodecTypes['pg/bool@1']['input'];
      readonly mime_type: CodecTypes['pg/text@1']['input'] | null;
      readonly sign_request_id: CodecTypes['pg/uuid@1']['input'];
      readonly type: 'ORIGINAL' | 'SIGNED' | 'ATTACHMENT';
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly sign_requests: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly reference_id: CodecTypes['pg/text@1']['input'];
      readonly rejected_at: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly rejection_reason: CodecTypes['pg/text@1']['input'] | null;
      readonly signed_at: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly signer_user_id: CodecTypes['pg/text@1']['input'];
      readonly status: 'PENDING' | 'PROCESSING' | 'SIGNED' | 'REJECTED' | 'FAILED' | 'CANCELLED';
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly village_id: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly signature_placements: {
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly document_id: CodecTypes['pg/uuid@1']['input'];
      readonly height: CodecTypes['pg/float8@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly page: CodecTypes['pg/int4@1']['input'];
      readonly sequence: CodecTypes['pg/int4@1']['input'];
      readonly sign_request_id: CodecTypes['pg/uuid@1']['input'];
      readonly signer_user_id: CodecTypes['pg/text@1']['input'];
      readonly type: 'SIGNATURE' | 'INITIAL' | 'STAMP' | 'QR_CODE';
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly width: CodecTypes['pg/float8@1']['input'];
      readonly x: CodecTypes['pg/float8@1']['input'];
      readonly y: CodecTypes['pg/float8@1']['input'];
    };
    readonly signatures: {
      readonly algorithm: CodecTypes['pg/text@1']['input'];
      readonly certificate_issuer: CodecTypes['pg/text@1']['input'] | null;
      readonly certificate_serial: CodecTypes['pg/text@1']['input'] | null;
      readonly document_hash: CodecTypes['pg/text@1']['input'];
      readonly document_id: CodecTypes['pg/uuid@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly sign_request_id: CodecTypes['pg/uuid@1']['input'];
      readonly signature_value: CodecTypes['pg/text@1']['input'];
      readonly signed_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly signer_user_id: CodecTypes['pg/text@1']['input'];
    };
    readonly signer_credentials: {
      readonly active: CodecTypes['pg/bool@1']['input'];
      readonly created_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly failed_attempt: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly locked_until: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly pin_hash: CodecTypes['pg/text@1']['input'];
      readonly updated_at: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly user_id: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly audit_logs: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly sign_request_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: true;
                  readonly typeRef: 'Uuid';
                };
                readonly actor_user_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly action: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly ip_address: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly user_agent: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly metadata: {
                  readonly nativeType: 'json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'audit_logs_sign_request_id_idx_caa2feef';
                  readonly prefix: 'audit_logs_sign_request_id_idx';
                  readonly columns: readonly ['sign_request_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'audit_logs_actor_user_id_idx_c46ca325';
                  readonly prefix: 'audit_logs_actor_user_id_idx';
                  readonly columns: readonly ['actor_user_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'audit_logs_action_idx_cd0d2116';
                  readonly prefix: 'audit_logs_action_idx';
                  readonly columns: readonly ['action'];
                  readonly unique: false;
                },
                {
                  readonly name: 'audit_logs_created_at_idx_225d8c0f';
                  readonly prefix: 'audit_logs_created_at_idx';
                  readonly columns: readonly ['created_at'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'audit_logs';
                    readonly columns: readonly ['sign_request_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'sign_requests';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly documents: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly sign_request_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly file_key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly hash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly mime_type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly file_size: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly locked: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'documents_sign_request_id_idx_caa2feef';
                  readonly prefix: 'documents_sign_request_id_idx';
                  readonly columns: readonly ['sign_request_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'documents_type_idx_b6b604ea';
                  readonly prefix: 'documents_type_idx';
                  readonly columns: readonly ['type'];
                  readonly unique: false;
                },
                {
                  readonly name: 'documents_created_at_idx_225d8c0f';
                  readonly prefix: 'documents_created_at_idx';
                  readonly columns: readonly ['created_at'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'documents';
                    readonly columns: readonly ['sign_request_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'sign_requests';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly sign_requests: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly reference_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly signer_user_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly village_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly rejection_reason: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly signed_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly rejected_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['reference_id'] }];
              indexes: readonly [
                {
                  readonly name: 'sign_requests_signer_user_id_idx_cda3000a';
                  readonly prefix: 'sign_requests_signer_user_id_idx';
                  readonly columns: readonly ['signer_user_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'sign_requests_status_idx_e98638ab';
                  readonly prefix: 'sign_requests_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
                {
                  readonly name: 'sign_requests_village_id_idx_baafdf98';
                  readonly prefix: 'sign_requests_village_id_idx';
                  readonly columns: readonly ['village_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'sign_requests_created_at_idx_225d8c0f';
                  readonly prefix: 'sign_requests_created_at_idx';
                  readonly columns: readonly ['created_at'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly signature_placements: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly sign_request_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly document_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly signer_user_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'SIGNATURE'>;
                  };
                };
                readonly page: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly x: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly y: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly width: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly height: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly sequence: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['document_id', 'signer_user_id', 'sequence'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'signature_placements_sign_request_id_idx_caa2feef';
                  readonly prefix: 'signature_placements_sign_request_id_idx';
                  readonly columns: readonly ['sign_request_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'signature_placements_document_id_idx_d3d0944e';
                  readonly prefix: 'signature_placements_document_id_idx';
                  readonly columns: readonly ['document_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'signature_placements_signer_user_id_idx_cda3000a';
                  readonly prefix: 'signature_placements_signer_user_id_idx';
                  readonly columns: readonly ['signer_user_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'signature_placements';
                    readonly columns: readonly ['sign_request_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'sign_requests';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'signature_placements';
                    readonly columns: readonly ['document_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'documents';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly signatures: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly sign_request_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly document_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly signer_user_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly document_hash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly algorithm: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly signature_value: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly certificate_serial: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly certificate_issuer: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly signed_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'signatures_sign_request_id_idx_caa2feef';
                  readonly prefix: 'signatures_sign_request_id_idx';
                  readonly columns: readonly ['sign_request_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'signatures_document_id_idx_d3d0944e';
                  readonly prefix: 'signatures_document_id_idx';
                  readonly columns: readonly ['document_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'signatures_signer_user_id_idx_cda3000a';
                  readonly prefix: 'signatures_signer_user_id_idx';
                  readonly columns: readonly ['signer_user_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'signatures_signed_at_idx_5cd80742';
                  readonly prefix: 'signatures_signed_at_idx';
                  readonly columns: readonly ['signed_at'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'signatures';
                    readonly columns: readonly ['sign_request_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'sign_requests';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'signatures';
                    readonly columns: readonly ['document_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'documents';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly signer_credentials: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly typeRef: 'Uuid';
                };
                readonly user_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly pin_hash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly failed_attempt: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly locked_until: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updated_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['user_id'] }];
              indexes: readonly [
                {
                  readonly name: 'signer_credentials_active_idx_8af4daed';
                  readonly prefix: 'signer_credentials_active_idx';
                  readonly columns: readonly ['active'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly AuditAction: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'SIGN_REQUEST_CREATED',
                'DOCUMENT_CREATED',
                'DOCUMENT_OPENED',
                'PLACEMENT_CREATED',
                'PLACEMENT_UPDATED',
                'SIGN_ATTEMPT',
                'PIN_FAILED',
                'SIGNED',
                'REJECTED',
                'FAILED',
                'CANCELLED',
              ];
            };
            readonly DocumentType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ORIGINAL', 'SIGNED', 'ATTACHMENT'];
            };
            readonly PlacementType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['SIGNATURE', 'INITIAL', 'STAMP', 'QR_CODE'];
            };
            readonly SignRequestStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'PENDING',
                'PROCESSING',
                'SIGNED',
                'REJECTED',
                'FAILED',
                'CANCELLED',
              ];
            };
          };
        };
      };
    };
    readonly types: {
      readonly Uuid: {
        readonly kind: 'codec-instance';
        readonly codecId: 'pg/uuid@1';
        readonly nativeType: 'uuid';
        readonly typeParams: Record<string, never>;
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly sign_requests: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SignRequest';
    };
    readonly documents: { readonly namespace: 'public' & NamespaceId; readonly model: 'Document' };
    readonly signature_placements: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SignaturePlacement';
    };
    readonly signatures: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Signature';
    };
    readonly signer_credentials: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SignerCredential';
    };
    readonly audit_logs: { readonly namespace: 'public' & NamespaceId; readonly model: 'AuditLog' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly AuditLog: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly signRequestId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly actorUserId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly action: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ipAddress: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userAgent: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly metadata: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly signRequest: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SignRequest';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['signRequestId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'audit_logs';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly signRequestId: { readonly column: 'sign_request_id' };
                readonly actorUserId: { readonly column: 'actor_user_id' };
                readonly action: { readonly column: 'action' };
                readonly ipAddress: { readonly column: 'ip_address' };
                readonly userAgent: { readonly column: 'user_agent' };
                readonly metadata: { readonly column: 'metadata' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly Document: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly signRequestId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fileKey: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly hash: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly mimeType: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fileSize: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly locked: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly placements: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SignaturePlacement';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['documentId'];
                };
              };
              readonly signRequest: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SignRequest';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['signRequestId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly signatures: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Signature';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['documentId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'documents';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly signRequestId: { readonly column: 'sign_request_id' };
                readonly type: { readonly column: 'type' };
                readonly fileKey: { readonly column: 'file_key' };
                readonly hash: { readonly column: 'hash' };
                readonly mimeType: { readonly column: 'mime_type' };
                readonly fileSize: { readonly column: 'file_size' };
                readonly locked: { readonly column: 'locked' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly Signature: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly signRequestId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly documentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly signerUserId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly documentHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly algorithm: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly signatureValue: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly certificateSerial: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly certificateIssuer: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly signedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly document: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Document';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['documentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly signRequest: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SignRequest';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['signRequestId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'signatures';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly signRequestId: { readonly column: 'sign_request_id' };
                readonly documentId: { readonly column: 'document_id' };
                readonly signerUserId: { readonly column: 'signer_user_id' };
                readonly documentHash: { readonly column: 'document_hash' };
                readonly algorithm: { readonly column: 'algorithm' };
                readonly signatureValue: { readonly column: 'signature_value' };
                readonly certificateSerial: { readonly column: 'certificate_serial' };
                readonly certificateIssuer: { readonly column: 'certificate_issuer' };
                readonly signedAt: { readonly column: 'signed_at' };
              };
            };
          };
          readonly SignaturePlacement: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly signRequestId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly documentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly signerUserId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly page: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly x: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly y: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly width: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly height: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly sequence: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly document: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Document';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['documentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly signRequest: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SignRequest';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['signRequestId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'signature_placements';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly signRequestId: { readonly column: 'sign_request_id' };
                readonly documentId: { readonly column: 'document_id' };
                readonly signerUserId: { readonly column: 'signer_user_id' };
                readonly type: { readonly column: 'type' };
                readonly page: { readonly column: 'page' };
                readonly x: { readonly column: 'x' };
                readonly y: { readonly column: 'y' };
                readonly width: { readonly column: 'width' };
                readonly height: { readonly column: 'height' };
                readonly sequence: { readonly column: 'sequence' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly SignerCredential: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly pinHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly failedAttempt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly lockedUntil: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly active: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'signer_credentials';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'user_id' };
                readonly pinHash: { readonly column: 'pin_hash' };
                readonly failedAttempt: { readonly column: 'failed_attempt' };
                readonly lockedUntil: { readonly column: 'locked_until' };
                readonly active: { readonly column: 'active' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
              };
            };
          };
          readonly SignRequest: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly referenceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly signerUserId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly villageId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rejectionReason: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly signedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly rejectedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly auditLogs: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AuditLog';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['signRequestId'];
                };
              };
              readonly documents: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Document';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['signRequestId'];
                };
              };
              readonly placements: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SignaturePlacement';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['signRequestId'];
                };
              };
              readonly signatures: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Signature';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['signRequestId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'sign_requests';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly referenceId: { readonly column: 'reference_id' };
                readonly signerUserId: { readonly column: 'signer_user_id' };
                readonly villageId: { readonly column: 'village_id' };
                readonly status: { readonly column: 'status' };
                readonly rejectionReason: { readonly column: 'rejection_reason' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly updatedAt: { readonly column: 'updated_at' };
                readonly signedAt: { readonly column: 'signed_at' };
                readonly rejectedAt: { readonly column: 'rejected_at' };
              };
            };
          };
        };
        readonly enum: {
          readonly SignRequestStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'PROCESSING'; readonly value: 'PROCESSING' },
              { readonly name: 'SIGNED'; readonly value: 'SIGNED' },
              { readonly name: 'REJECTED'; readonly value: 'REJECTED' },
              { readonly name: 'FAILED'; readonly value: 'FAILED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
            ];
          };
          readonly DocumentType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ORIGINAL'; readonly value: 'ORIGINAL' },
              { readonly name: 'SIGNED'; readonly value: 'SIGNED' },
              { readonly name: 'ATTACHMENT'; readonly value: 'ATTACHMENT' },
            ];
          };
          readonly PlacementType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'SIGNATURE'; readonly value: 'SIGNATURE' },
              { readonly name: 'INITIAL'; readonly value: 'INITIAL' },
              { readonly name: 'STAMP'; readonly value: 'STAMP' },
              { readonly name: 'QR_CODE'; readonly value: 'QR_CODE' },
            ];
          };
          readonly AuditAction: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'SIGN_REQUEST_CREATED'; readonly value: 'SIGN_REQUEST_CREATED' },
              { readonly name: 'DOCUMENT_CREATED'; readonly value: 'DOCUMENT_CREATED' },
              { readonly name: 'DOCUMENT_OPENED'; readonly value: 'DOCUMENT_OPENED' },
              { readonly name: 'PLACEMENT_CREATED'; readonly value: 'PLACEMENT_CREATED' },
              { readonly name: 'PLACEMENT_UPDATED'; readonly value: 'PLACEMENT_UPDATED' },
              { readonly name: 'SIGN_ATTEMPT'; readonly value: 'SIGN_ATTEMPT' },
              { readonly name: 'PIN_FAILED'; readonly value: 'PIN_FAILED' },
              { readonly name: 'SIGNED'; readonly value: 'SIGNED' },
              { readonly name: 'REJECTED'; readonly value: 'REJECTED' },
              { readonly name: 'FAILED'; readonly value: 'FAILED' },
              { readonly name: 'CANCELLED'; readonly value: 'CANCELLED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'audit_logs';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'documents';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'documents';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'sign_requests';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'sign_requests';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'signature_placements';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'signature_placements';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'signatures';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'signer_credentials';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'signer_credentials';
            readonly column: 'updated_at';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'instantNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'instantNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
